### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dustinwinski** [Sh4yy/OrangeDB#1]
Hello!

I'm working on a simple project pretty similar in scope (I think) to OrangeDB. I'd actually like to contribute instead of duplicate efforts if possible. My only question is explicit licensing. Do you have a license for this project? May I recommend the MIT license?

**Comment by Sh4yy** [comment]
Hey Dustin,

Thank you for your interest in this project. I went ahead and added MIT license to this project.
For further questions feel free to contact me shayan@shayy.org.

Best,
